# Generated by Django 4.2.10 on 2024-03-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_name_alter_recipe_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='icons/items')),
            ],
        ),
        migrations.CreateModel(
            name='VariantOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='VariantInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fabric_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='input',
            field=models.ManyToManyField(blank=True, to='main.variantinput'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='output',
            field=models.ManyToManyField(blank=True, to='main.variantoutput'),
        ),
    ]
