# Generated by Django 4.2.10 on 2024-03-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_image_variantoutput_variantinput_item_item_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='icons/fabrics')),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ItemImage',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fabric_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fabricimage'),
        ),
    ]
