# Generated by Django 4.2.10 on 2024-03-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_fabricimage_rename_image_itemimage_remove_item_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
                ('fabric_image', models.ImageField(upload_to='icons/fabrics')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='fabric_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=123, upload_to='icons/items'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FabricImage',
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.AddField(
            model_name='recipe',
            name='fabric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fabric'),
        ),
    ]
