# Generated by Django 4.2.10 on 2024-03-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_fabric_remove_recipe_fabric_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantinput',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='variantoutput',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
