# Generated by Django 4.2.11 on 2024-03-24 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_variantinput_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='base_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
