# Generated by Django 4.2.11 on 2024-03-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recipe_base_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='base_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
    ]
